// Package startup manages only this application's current-user Run entry.
package startup

import (
	"errors"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/sys/windows/registry"
)

const runKey = `Software\Microsoft\Windows\CurrentVersion\Run`
const valueName = "Rabbit Modem Monitoring"

func command() (string, error) {
	exe, err := os.Executable()
	if err != nil || !filepath.IsAbs(exe) || strings.ContainsAny(exe, "\"\r\n") {
		return "", errors.New("Lokasi executable tidak valid untuk startup")
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	return `"` + exe + `"`, nil
}

// Status is read-only. Moving the portable executable requires re-enabling.
func Status() (bool, error) {
	k, err := registry.OpenKey(registry.CURRENT_USER, runKey, registry.QUERY_VALUE)
	if errors.Is(err, registry.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, errors.New("Pengaturan startup Windows tidak dapat dibaca")
	}
	defer k.Close()
	value, _, err := k.GetStringValue(valueName)
	if errors.Is(err, registry.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, errors.New("Entri startup tidak valid; aktifkan ulang toggle untuk memperbaiki")
	}
	expected, err := command()
	if err != nil {
		return false, err
	}
	if !strings.EqualFold(value, expected) {
		return false, errors.New("Startup menunjuk lokasi EXE lain; aktifkan toggle untuk memakai lokasi sekarang")
	}
	return true, nil
}

func Set(enabled bool) error {
	if !enabled {
		k, err := registry.OpenKey(registry.CURRENT_USER, runKey, registry.SET_VALUE)
		if errors.Is(err, registry.ErrNotExist) {
			return nil
		}
		if err != nil {
			return errors.New("Pengaturan startup tidak dapat diubah")
		}
		defer k.Close()
		if err := k.DeleteValue(valueName); err != nil && !errors.Is(err, registry.ErrNotExist) {
			return errors.New("Startup gagal dinonaktifkan")
		}
		return nil
	}
	value, err := command()
	if err != nil {
		return err
	}
	// Never register the temporary executable generated by go run/debuggers.
	path := strings.ToLower(strings.ReplaceAll(value, `\`, "/"))
	if strings.Contains(path, "/go-build") || strings.Contains(path, "__debug_bin") {
		return errors.New("Jalankan file EXE portable dari lokasi tetap sebelum mengaktifkan startup")
	}
	k, _, err := registry.CreateKey(registry.CURRENT_USER, runKey, registry.SET_VALUE)
	if err != nil {
		return errors.New("Startup gagal diaktifkan; akses registry ditolak")
	}
	defer k.Close()
	if k.SetStringValue(valueName, value) != nil {
		return errors.New("Startup gagal disimpan")
	}
	return nil
}
